name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: yarn install, yarn build
        run: |
          yarn install
          yarn build

      - name: pack the files
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -r extension.zip build

      - name: upload and publish to chrome store
        run: |
          npx chrome-webstore-upload-cli upload --source extension.zip --extension-id ${{ secrets.EXTENSION_ID }} --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --refresh-token ${{ secrets.REFRESH_TOKEN }}
          npx chrome-webstore-upload-cli publish --client-id ${{ secrets.CLIENT_ID }}
